script:
  id_script: Ventes_Aggregat_CumulGlissant
  description: Calcul des cumuls glissants sur 12 mois pour le domaine ventes

  parametres_env:
    TBL_HISTO: £BQ_HISTO.ventes_histo
    TBL_AGGR: £BQ_HISTO.ventes_aggr_mensuel_canal

  jobs:
    - job_id: job.run.sql
      description: Recalcule le cumul glissant 12 mois
      parametres:
        Plateforme: BQ
        Requete: Ventes_aggregat_cumul_glissant_12m.gql
