-- Création de la table SOCLE ventes (BigQuery)
CREATE TABLE IF NOT EXISTS £BQ_SOCLE.ventes (
  id_vente                            STRING NOT NULL
  id_client                           STRING
  id_produit                          STRING
  id_commercial                       STRING
  date_vente                          DATE
  canal                               STRING
  montant                             NUMERIC
  commission                          NUMERIC
  statut                              STRING
  date_maj                            TIMESTAMP
);
