script:
  id_script: Clients_Installation_CreationTableAggregat
  description: Création initiale de la table agrégat clients_aggr_mensuel (BQ)

  parametres_env:
    TBL_AGGR: £BQ_HISTO.clients_aggr_mensuel

  jobs:
    - job_id: job.run.sql
      description: Crée la table agrégat clients_aggr_mensuel sur BQ
      parametres:
        Plateforme: BQ
        Requete: Clients_installation_creation_table_aggregat.gql
