-- Création de la table agrégat commandes_aggr_journalier (BigQuery)
CREATE TABLE IF NOT EXISTS £BQ_HISTO.commandes_aggr_journalier (
  periode                  STRING         NOT NULL,
  nb_enregistrements       INT64,
  cumul_12m                INT64,
  date_calcul              TIMESTAMP
);
