script:
  id_script: Portabilite_Import_DeplacementTravail
  description: Déplacement des fichiers portabilite de la zone d'entrée vers la zone de travail

  parametres_env:
    REP_IN: C:\data\portabilite\in
    REP_WORK: C:\data\portabilite\work
    MASQUE_PORTABILITE: "^portages_\d{8}\.csv$"

  jobs:
    - job_id: job.fichier.manipulation
      description: Déplace les fichiers vers la zone de travail
      parametres:
        Source: £REP_IN
        Cible: £REP_WORK
        Masque: £MASQUE_PORTABILITE
        Mode: deplacement
