-- Insertion agrégat journalier dans produits_histo (BigQuery)
INSERT INTO £BQ_HISTO.produits_histo (
  id_produit,
  date_agregat,
  nb_enregistrements,
  date_maj
)
SELECT
  'produits' AS id_produit,
  CURRENT_DATE() AS date_agregat,
  COUNT(*) AS nb_enregistrements,
  CURRENT_TIMESTAMP() AS date_maj
FROM £BQ_SOCLE.produits
WHERE DATE(date_maj) = CURRENT_DATE();
