script:
  id_script: Commandes_Aggregat_CumulGlissant
  description: Calcul des cumuls glissants sur 12 mois pour le domaine commandes

  parametres_env:
    TBL_HISTO: £BQ_HISTO.commandes_histo
    TBL_AGGR: £BQ_HISTO.commandes_aggr_journalier

  jobs:
    - job_id: job.run.sql
      description: Recalcule le cumul glissant 12 mois
      parametres:
        Plateforme: BQ
        Requete: Commandes_aggregat_cumul_glissant_12m.gql
