script:
  id_script: Fraude_Import_RapatriementSFTP
  description: Rapatriement des fichiers fraude depuis le SFTP source vers la zone d'entrée

  parametres_env:
    SFTP_SOURCE: sftp://fraud-engine/alertes/in
    REP_IN: C:\data\fraude\in

  jobs:
    - job_id: job.externe.import
      description: Récupère les fichiers fraude depuis le SFTP
      parametres:
        Source: £SFTP_SOURCE
        Cible: £REP_IN
        Type: sftp
