-- Chargement des fichiers marketing dans la table staging BigQuery
LOAD DATA OVERWRITE £BQ_TMP.staging_campagnes
FROM FILES (
  format = 'CSV',
  uris = ['gs://telecom-landing/marketing/*.csv'],
  skip_leading_rows = 1,
  field_delimiter = ';'
);
