script:
  id_script: Portabilite_Installation_CreationTableSocle
  description: Création initiale de la table SOCLE portages (TD)

  parametres_env:
    TBL_SOCLE: £TD_SOCLE.portages

  jobs:
    - job_id: job.run.sql
      description: Crée la table SOCLE portages sur TD
      parametres:
        Plateforme: TD
        Requete: Portabilite_installation_creation_table_socle.dql
