script:
  id_script: Produits_Installation_CreationTableStaging
  description: Création initiale de la table staging staging_produits (BQ)

  parametres_env:
    TBL_STAGING: £BQ_TMP.staging_produits

  jobs:
    - job_id: job.run.sql
      description: Crée la table staging staging_produits sur BQ
      parametres:
        Plateforme: BQ
        Requete: Produits_installation_creation_table_staging.gql
