-- Chargement des fichiers clients dans la table staging BigQuery
LOAD DATA OVERWRITE £BQ_TMP.staging_clients
FROM FILES (
  format = 'CSV',
  uris = ['gs://telecom-landing/clients/*.csv'],
  skip_leading_rows = 1,
  field_delimiter = ';'
);
