script:
  id_script: Portabilite_Installation_CreationTableStaging
  description: Création initiale de la table staging staging_portages (TD)

  parametres_env:
    TBL_STAGING: £TD_TMP.staging_portages

  jobs:
    - job_id: job.run.sql
      description: Crée la table staging staging_portages sur TD
      parametres:
        Plateforme: TD
        Requete: Portabilite_installation_creation_table_staging.dql
