script:
  id_script: Recouvrement_Installation_CreationTableStaging
  description: Création initiale de la table staging staging_creances (TD)

  parametres_env:
    TBL_STAGING: £TD_TMP.staging_creances

  jobs:
    - job_id: job.run.sql
      description: Crée la table staging staging_creances sur TD
      parametres:
        Plateforme: TD
        Requete: Recouvrement_installation_creation_table_staging.dql
