script:
  id_script: Interconnexion_Import_DeplacementTravail
  description: Déplacement des fichiers interconnexion de la zone d'entrée vers la zone de travail

  parametres_env:
    REP_IN: C:\data\interconnexion\in
    REP_WORK: C:\data\interconnexion\work
    MASQUE_INTERCONNEXION: "^interconnexion_\d{8}\.csv$"

  jobs:
    - job_id: job.fichier.manipulation
      description: Déplace les fichiers vers la zone de travail
      parametres:
        Source: £REP_IN
        Cible: £REP_WORK
        Masque: £MASQUE_INTERCONNEXION
        Mode: deplacement
