script:
  id_script: Consommations_Alimentation_ChargementsParalleles
  description: Chargement parallèle du SOCLE et de la table historique consommations

  parametres_env:
    TBL_SOCLE: £TD_SOCLE.cdr_voix
    TBL_HISTO: £TD_HISTO.cdr_voix_histo

  jobs:
    - job_id: job.process.parallele
      description: Alimente SOCLE et HISTO simultanément
      jobs:
        - job_id: job.run.sql
          description: Upsert SOCLE cdr_voix
          parametres:
            Plateforme: TD
            Requete: Consommations_alimentation_upsert_socle.dql

        - job_id: job.run.sql
          description: Insert historique cdr_voix_histo
          parametres:
            Plateforme: TD
            Requete: Consommations_alimentation_insert_histo.dql
