-- Création de la table agrégat clients_aggr_mensuel (BigQuery)
CREATE TABLE IF NOT EXISTS £BQ_HISTO.clients_aggr_mensuel (
  periode                  STRING         NOT NULL,
  nb_enregistrements       INT64,
  cumul_12m                INT64,
  date_calcul              TIMESTAMP
);
