script:
  id_script: Clients_Aggregat_CumulGlissant
  description: Calcul des cumuls glissants sur 12 mois pour le domaine clients

  parametres_env:
    TBL_HISTO: £BQ_HISTO.clients_histo
    TBL_AGGR: £BQ_HISTO.clients_aggr_mensuel

  jobs:
    - job_id: job.run.sql
      description: Recalcule le cumul glissant 12 mois
      parametres:
        Plateforme: BQ
        Requete: Clients_aggregat_cumul_glissant_12m.gql
