script:
  id_script: Produits_Import_RapatriementSFTP
  description: Rapatriement des fichiers produits depuis le SFTP source vers la zone d'entrée

  parametres_env:
    SFTP_SOURCE: sftp://catalogue-system/produits/in
    REP_IN: C:\data\produits\in

  jobs:
    - job_id: job.externe.import
      description: Récupère les fichiers produits depuis le SFTP
      parametres:
        Source: £SFTP_SOURCE
        Cible: £REP_IN
        Type: sftp
