script:
  id_script: Finance_Aggregat_CumulGlissant
  description: Calcul des cumuls glissants sur 12 mois pour le domaine finance

  parametres_env:
    TBL_HISTO: £BQ_HISTO.comptes_financiers_histo
    TBL_AGGR: £BQ_HISTO.finance_aggr_mensuel_rubrique

  jobs:
    - job_id: job.run.sql
      description: Recalcule le cumul glissant 12 mois
      parametres:
        Plateforme: BQ
        Requete: Finance_aggregat_cumul_glissant_12m.gql
