-- Chargement des fichiers contrats dans la table staging BigQuery
LOAD DATA OVERWRITE £BQ_TMP.staging_contrats
FROM FILES (
  format = 'CSV',
  uris = ['gs://telecom-landing/contrats/*.csv'],
  skip_leading_rows = 1,
  field_delimiter = ';'
);
