script:
  id_script: Equipements_Installation_CreationTableAggregat
  description: Création initiale de la table agrégat equipements_aggr_parc_mensuel (TD)

  parametres_env:
    TBL_AGGR: £TD_HISTO.equipements_aggr_parc_mensuel

  jobs:
    - job_id: job.run.sql
      description: Crée la table agrégat equipements_aggr_parc_mensuel sur TD
      parametres:
        Plateforme: TD
        Requete: Equipements_installation_creation_table_aggregat.dql
