script:
  id_script: Marketing_Installation_CreationTableAggregat
  description: Création initiale de la table agrégat campagnes_aggr_performance_mensuel (BQ)

  parametres_env:
    TBL_AGGR: £BQ_HISTO.campagnes_aggr_performance_mensuel

  jobs:
    - job_id: job.run.sql
      description: Crée la table agrégat campagnes_aggr_performance_mensuel sur BQ
      parametres:
        Plateforme: BQ
        Requete: Marketing_installation_creation_table_aggregat.gql
