script:
  id_script: Fraude_Installation_CreationTableSocle
  description: Création initiale de la table SOCLE alertes_fraude (TD)

  parametres_env:
    TBL_SOCLE: £TD_SOCLE.alertes_fraude

  jobs:
    - job_id: job.run.sql
      description: Crée la table SOCLE alertes_fraude sur TD
      parametres:
        Plateforme: TD
        Requete: Fraude_installation_creation_table_socle.dql
