script:
  id_script: ServiceClient_Installation_CreationTableSocle
  description: Création initiale de la table SOCLE interactions (BQ)

  parametres_env:
    TBL_SOCLE: £BQ_SOCLE.interactions

  jobs:
    - job_id: job.run.sql
      description: Crée la table SOCLE interactions sur BQ
      parametres:
        Plateforme: BQ
        Requete: ServiceClient_installation_creation_table_socle.gql
