-- Création de la table agrégat ventes_aggr_mensuel_canal (BigQuery)
CREATE TABLE IF NOT EXISTS £BQ_HISTO.ventes_aggr_mensuel_canal (
  periode                  STRING         NOT NULL,
  nb_enregistrements       INT64,
  cumul_12m                INT64,
  date_calcul              TIMESTAMP
);
