-- Chargement des fichiers produits dans la table staging BigQuery
LOAD DATA OVERWRITE £BQ_TMP.staging_produits
FROM FILES (
  format = 'CSV',
  uris = ['gs://telecom-landing/produits/*.csv'],
  skip_leading_rows = 1,
  field_delimiter = ';'
);
