-- Création de la table staging staging_clients (BigQuery)
CREATE TABLE IF NOT EXISTS £BQ_TMP.staging_clients (
  id_client                           STRING NOT NULL
  nom                                 STRING
  prenom                              STRING
  email                               STRING
  telephone                           STRING
  date_naissance                      DATE
  segment                             STRING
  statut                              STRING
  date_maj                            TIMESTAMP
)
OPTIONS (expiration_timestamp = NULL);
