script:
  id_script: Incidents_Installation_CreationTableSocle
  description: Création initiale de la table SOCLE incidents (TD)

  parametres_env:
    TBL_SOCLE: £TD_SOCLE.incidents

  jobs:
    - job_id: job.run.sql
      description: Crée la table SOCLE incidents sur TD
      parametres:
        Plateforme: TD
        Requete: Incidents_installation_creation_table_socle.dql
