script:
  id_script: Paiements_Installation_CreationTableSocle
  description: Création initiale de la table SOCLE paiements (BQ)

  parametres_env:
    TBL_SOCLE: £BQ_SOCLE.paiements

  jobs:
    - job_id: job.run.sql
      description: Crée la table SOCLE paiements sur BQ
      parametres:
        Plateforme: BQ
        Requete: Paiements_installation_creation_table_socle.gql
